language: python
python:
  - "2.7"
  - "3.4"
  - "3.6"
before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq liblzo2-dev
 - pip install -e git+https://github.com/flowersteam/naminggamesal.git@develop#egg=naminggamesal
 - docker pull giovtorres/docker-centos7-slurm:latest
 - docker run -itd -h ernie --name docker_slurm giovtorres/docker-centos7-slurm:latest
 - docker exec -it docker_slurm yum -y install openssh-server openssh-clients
 - docker exec -it docker_slurm ssh-keygen -A
 - docker exec -it docker_slurm bash -c 'echo "PermitRootLogin yes" > /etc/ssh/sshd_config'
 - docker exec -it docker_slurm bash -c "echo 'root:dockerslurm' | chpasswd"
 - docker exec -it docker_slurm /usr/sbin/sshd -D

install:
  - pip install codecov pytest-cov
  - pip install -r requirements.txt
  - python setup.py develop
script: pytest --cov=./
after_success:
  - codecov
